image: ubuntu

build: off

build_script:
  - pwd && ls -la
  - which ruby && ruby --version
  - rvm use 2.4.1 && which ruby && ruby --version
  - rvm use 2.4.1 && chmod +x ./build_gem.sh && ./build_gem.sh

artifacts:
    - path: '**\.build\*.gem'